# Generated by Django 4.0.4 on 2022-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
